export const DELETE_POD_INVALID = 'DELETE_POD_INVALID';
export const DELETE_POD_REQUESTING = 'DELETE_POD_REQUESTING';
export const DELETE_POD_SUCCESS = 'DELETE_POD_SUCCESS';
export const DELETE_POD_FAILURE = 'DELETE_POD_FAILURE';
