export const GET_POD_INVALID = 'GET_POD_INVALID';
export const GET_POD_REQUESTING = 'GET_POD_REQUESTING';
export const GET_POD_SUCCESS = 'GET_POD_SUCCESS';
export const GET_POD_FAILURE = 'GET_POD_FAILURE';
