export const ADD_STORAGE_INVALID = 'ADD_STORAGE_INVALID';
export const ADD_STORAGE_REQUESTING = 'ADD_STORAGE_REQUESTING';
export const ADD_STORAGE_SUCCESS = 'ADD_STORAGE_SUCCESS';
export const ADD_STORAGE_FAILURE = 'ADD_STORAGE_FAILURE';
