export const DELETE_STORAGE_INVALID = 'DELETE_STORAGE_INVALID';
export const DELETE_STORAGE_REQUESTING = 'DELETE_STORAGE_REQUESTING';
export const DELETE_STORAGE_SUCCESS = 'DELETE_STORAGE_SUCCESS';
export const DELETE_STORAGE_FAILURE = 'DELETE_STORAGE_FAILURE';
