export const GET_COUNT_SERVICES_INVALID = 'GET_COUNT_SERVICES_INVALID';
export const GET_COUNT_SERVICES_REQUESTING = 'GET_COUNT_SERVICES_REQUESTING';
export const GET_COUNT_SERVICES_SUCCESS = 'GET_COUNT_SERVICES_SUCCESS';
export const GET_COUNT_SERVICES_FAILURE = 'GET_COUNT_SERVICES_FAILURE';
