export const GET_CPU_HISTORY_PER_NODES_STATISTIC_INVALID =
  'GET_CPU_HISTORY_PER_NODES_STATISTIC_INVALID';
export const GET_CPU_HISTORY_PER_NODES_STATISTIC_REQUESTING =
  'GET_CPU_HISTORY_PER_NODES_STATISTIC_REQUESTING';
export const GET_CPU_HISTORY_PER_NODES_STATISTIC_SUCCESS =
  'GET_CPU_HISTORY_PER_NODES_STATISTIC_SUCCESS';
export const GET_CPU_HISTORY_PER_NODES_STATISTIC_FAILURE =
  'GET_CPU_HISTORY_PER_NODES_STATISTIC_FAILURE';
