export const GET_CPU_STATISTIC_INVALID = 'GET_CPU_STATISTIC_INVALID';
export const GET_CPU_STATISTIC_REQUESTING = 'GET_CPU_STATISTIC_REQUESTING';
export const GET_CPU_STATISTIC_SUCCESS = 'GET_CPU_STATISTIC_SUCCESS';
export const GET_CPU_STATISTIC_FAILURE = 'GET_CPU_STATISTIC_FAILURE';
