export const GET_COUNT_PODS_INVALID = 'GET_COUNT_PODS_INVALID';
export const GET_COUNT_PODS_REQUESTING = 'GET_COUNT_PODS_REQUESTING';
export const GET_COUNT_PODS_SUCCESS = 'GET_COUNT_PODS_SUCCESS';
export const GET_COUNT_PODS_FAILURE = 'GET_COUNT_PODS_FAILURE';
