export const GET_COUNT_DEPLOYMENTS_INVALID = 'GET_COUNT_DEPLOYMENTS_INVALID';
export const GET_COUNT_DEPLOYMENTS_REQUESTING =
  'GET_COUNT_DEPLOYMENTS_REQUESTING';
export const GET_COUNT_DEPLOYMENTS_SUCCESS = 'GET_COUNT_DEPLOYMENTS_SUCCESS';
export const GET_COUNT_DEPLOYMENTS_FAILURE = 'GET_COUNT_DEPLOYMENTS_FAILURE';
