export const GET_MEMORY_STATISTIC_INVALID = 'GET_MEMORY_STATISTIC_INVALID';
export const GET_MEMORY_STATISTIC_REQUESTING =
  'GET_MEMORY_STATISTIC_REQUESTING';
export const GET_MEMORY_STATISTIC_SUCCESS = 'GET_MEMORY_STATISTIC_SUCCESS';
export const GET_MEMORY_STATISTIC_FAILURE = 'GET_MEMORY_STATISTIC_FAILURE';
