export const GET_RESOURCES_INVALID = 'GET_RESOURCES_INVALID';
export const GET_RESOURCES_REQUESTING = 'GET_RESOURCES_REQUESTING';
export const GET_RESOURCES_SUCCESS = 'GET_RESOURCES_SUCCESS';
export const GET_RESOURCES_FAILURE = 'GET_RESOURCES_FAILURE';
