export const GET_STORAGE_STATISTIC_INVALID = 'GET_STORAGE_STATISTIC_INVALID';
export const GET_STORAGE_STATISTIC_REQUESTING =
  'GET_STORAGE_STATISTIC_REQUESTING';
export const GET_STORAGE_STATISTIC_SUCCESS = 'GET_STORAGE_STATISTIC_SUCCESS';
export const GET_STORAGE_STATISTIC_FAILURE = 'GET_STORAGE_STATISTIC_FAILURE';
