pipeline:
  docker:
    image: plugins/docker
    repo: exon/ch-ui
    tags: ${DRONE_COMMIT_BRANCH}-${DRONE_COMMIT_SHA:0:8}
    secrets: [ docker_username, docker_password]
    when:
      branch: dev-v*


  deploy:
    image: mastanggt/drone-kubernetes
    deploy_file: deploy.yaml
    deploy_image: exon/ch-ui:${DRONE_COMMIT_BRANCH}-${DRONE_COMMIT_SHA:0:8}
    secrets: [ kubernetes_cert, port, image, kubernetes_client, kubernetes_client_key, kubernetes_ip, web_api ]
    when:
      branch: dev-v*

