stages:
  - build
  - deploy

.create_tag: &create_tag
  before_script:
    - export TAG="${CI_COMMIT_SHA:0:8}"-${CI_PIPELINE_ID}

build-and-push-develop:
  <<: *create_tag
  image: docker:latest
  stage: build
  tags:
    - ui
  script:
    - docker login  ${DOCKER_REGISTRY} -u "$DOCKER_REGISTRY_USER" -p "$DOCKER_REGISTRY_PASSWORD"
    - docker build --pull --no-cache -t ${DOCKER_REGISTRY_IMAGE}:${TAG} .
    - docker push "${DOCKER_REGISTRY_IMAGE}:${TAG}"
    - docker rmi ${DOCKER_REGISTRY_IMAGE}:${TAG}
  only:
    - develop

deploy-to-kubernetes-develop:
  <<: *create_tag
  image: mastanggt/kubectl:latest
  stage: deploy
  environment:
    name: sandbox
  tags:
    - deploy
  script:
    - export IMAGE="$DOCKER_REGISTRY_IMAGE:${TAG}"
    - echo $SANDBOX_KUBE_CONFIG | base64 -d > admin.conf
    - cat deploy-template.yaml | envsubst > deploy.yaml
    - kubectl --kubeconfig=admin.conf replace -f deploy.yaml
  only:
    - develop
