sudo: required

language: go

env:
  global:
  - OWNER=containerum
  - NAME=ui
  - IMAGE_NAME=$OWNER/ui
  - HELM_URL=https://$OWNER.github.io/$NAME/charts

services:
  - docker

install:
  - curl https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get | bash
  - helm init --client-only
  - go get github.com/mikefarah/yq
  - sudo apt-get install jq

script:
  - docker build -t "$IMAGE_NAME" --build-arg SOURCE_TYPE=OFLINE .

before_deploy:
  - docker login -u="$DOCKER_LOGIN" -p="$DOCKER_PASSWORD"
  - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:latest"
  - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:${TRAVIS_TAG}"
  - yq write --inplace charts/$NAME/values.yaml image.tag "${TRAVIS_TAG}"
  - wget https://api.github.com/repos/containerum/$NAME/releases
  - cat releases | jq '.[].assets[].browser_download_url | select(. | test(".tgz")) | select(. | test("${NAME}"))' > download
  - touch latest
  - if [ $(cat releases | jq '. | length') != 0 ]; wget https://api.github.com/repos/containerum/$NAME/releases/latest; fi;
  - cat latest | jq '.assets[].browser_download_url | select(. | test("index.yaml"))' >> download
  - xargs -i wget -P charts '{}' < download
  - rm releases && rm latest && rm download
  - helm package charts/$NAME --version="${TRAVIS_TAG}" --dependency-update --destination charts
  - helm repo index --url $HELM_URL --merge charts/index.yaml charts

deploy:
  - provider: script
    script: docker push "${IMAGE_NAME}:latest" && docker push "${IMAGE_NAME}:${TRAVIS_TAG}"
    on:
      tags: true
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    on:
      tags: true
  - provider: releases
    api_key: $GITHUB_TOKEN
    file:
      - "charts/$NAME-${TRAVIS_TAG}.tgz"
      - "charts/index.yaml"
    skip_cleanup: true
    on:
      tags: true
