export const GET_SECRETS_INVALID = 'GET_SECRETS_INVALID';
export const GET_SECRETS_REQUESTING = 'GET_SECRETS_REQUESTING';
export const GET_SECRETS_SUCCESS = 'GET_SECRETS_SUCCESS';
export const GET_SECRETS_FAILURE = 'GET_SECRETS_FAILURE';
