export const GET_PODS_INVALID = 'GET_PODS_INVALID';
export const GET_PODS_REQUESTING = 'GET_PODS_REQUESTING';
export const GET_PODS_SUCCESS = 'GET_PODS_SUCCESS';
export const GET_PODS_FAILURE = 'GET_PODS_FAILURE';
