export const COUPON_PAY_INVALID = 'COUPON_PAY_INVALID';
export const COUPON_PAY_REQUESTING = 'COUPON_PAY_REQUESTING';
export const COUPON_PAY_SUCCESS = 'COUPON_PAY_SUCCESS';
export const COUPON_PAY_FAILURE = 'COUPON_PAY_FAILURE';
