export const GET_BALANCE_INVALID = 'GET_BALANCE_INVALID';
export const GET_BALANCE_REQUESTING = 'GET_BALANCE_REQUESTING';
export const GET_BALANCE_SUCCESS = 'GET_BALANCE_SUCCESS';
export const GET_BALANCE_FAILURE = 'GET_BALANCE_FAILURE';
