export const PAY_FOR_INVALID = 'PAY_FOR_INVALID';
export const PAY_FOR_REQUESTING = 'PAY_FOR_REQUESTING';
export const PAY_FOR_SUCCESS = 'PAY_FOR_SUCCESS';
export const PAY_FOR_FAILURE = 'PAY_FOR_FAILURE';
