export const CREATE_DEPLOYMENT_INVALID = 'CREATE_DEPLOYMENT_INVALID';
export const CREATE_DEPLOYMENT_REQUESTING = 'CREATE_DEPLOYMENT_REQUESTING';
export const CREATE_DEPLOYMENT_SUCCESS = 'CREATE_DEPLOYMENT_SUCCESS';
export const CREATE_DEPLOYMENT_FAILURE = 'CREATE_DEPLOYMENT_FAILURE';
