export const DELETE_DEPLOYMENT_INVALID = 'DELETE_DEPLOYMENT_INVALID';
export const DELETE_DEPLOYMENT_REQUESTING = 'DELETE_DEPLOYMENT_REQUESTING';
export const DELETE_DEPLOYMENT_SUCCESS = 'DELETE_DEPLOYMENT_SUCCESS';
export const DELETE_DEPLOYMENT_FAILURE = 'DELETE_DEPLOYMENT_FAILURE';
