export const GET_DEPLOYMENT_INVALID = 'GET_DEPLOYMENT_INVALID';
export const GET_DEPLOYMENT_REQUESTING = 'GET_DEPLOYMENT_REQUESTING';
export const GET_DEPLOYMENT_SUCCESS = 'GET_DEPLOYMENT_SUCCESS';
export const GET_DEPLOYMENT_FAILURE = 'GET_DEPLOYMENT_FAILURE';
