export const UPDATE_DEPLOYMENT_INVALID = 'UPDATE_DEPLOYMENT_INVALID';
export const UPDATE_DEPLOYMENT_REQUESTING = 'UPDATE_DEPLOYMENT_REQUESTING';
export const UPDATE_DEPLOYMENT_SUCCESS = 'UPDATE_DEPLOYMENT_SUCCESS';
export const UPDATE_DEPLOYMENT_FAILURE = 'UPDATE_DEPLOYMENT_FAILURE';
