export const GET_STORAGES_INVALID = 'GET_STORAGES_INVALID';
export const GET_STORAGES_REQUESTING = 'GET_STORAGES_REQUESTING';
export const GET_STORAGES_SUCCESS = 'GET_STORAGES_SUCCESS';
export const GET_STORAGES_FAILURE = 'GET_STORAGES_FAILURE';
