export const CREATE_SECRET_INVALID = 'CREATE_SECRET_INVALID';
export const CREATE_SECRET_REQUESTING = 'CREATE_SECRET_REQUESTING';
export const CREATE_SECRET_SUCCESS = 'CREATE_SECRET_SUCCESS';
export const CREATE_SECRET_FAILURE = 'CREATE_SECRET_FAILURE';
