export const DELETE_SECRET_INVALID = 'DELETE_SECRET_INVALID';
export const DELETE_SECRET_REQUESTING = 'DELETE_SECRET_REQUESTING';
export const DELETE_SECRET_SUCCESS = 'DELETE_SECRET_SUCCESS';
export const DELETE_SECRET_FAILURE = 'DELETE_SECRET_FAILURE';
