export const GET_SECRET_INVALID = 'GET_SECRET_INVALID';
export const GET_SECRET_REQUESTING = 'GET_SECRET_REQUESTING';
export const GET_SECRET_SUCCESS = 'GET_SECRET_SUCCESS';
export const GET_SECRET_FAILURE = 'GET_SECRET_FAILURE';
