export const GET_NAMESPACES_INVALID = 'GET_NAMESPACES_INVALID';
export const GET_NAMESPACES_REQUESTING = 'GET_NAMESPACES_REQUESTING';
export const GET_NAMESPACES_SUCCESS = 'GET_NAMESPACES_SUCCESS';
export const GET_NAMESPACES_FAILURE = 'GET_NAMESPACES_FAILURE';
