export const GET_NAMESPACES_TARIFFS_INVALID = 'GET_NAMESPACES_TARIFFS_INVALID';
export const GET_NAMESPACES_TARIFFS_REQUESTING =
  'GET_NAMESPACES_TARIFFS_REQUESTING';
export const GET_NAMESPACES_TARIFFS_SUCCESS = 'GET_NAMESPACES_TARIFFS_SUCCESS';
export const GET_NAMESPACES_TARIFFS_FAILURE = 'GET_NAMESPACES_TARIFFS_FAILURE';
