export const GET_NAMESPACES_USAGE_INVALID = 'GET_NAMESPACES_USAGE_INVALID';
export const GET_NAMESPACES_USAGE_REQUESTING =
  'GET_NAMESPACES_USAGE_REQUESTING';
export const GET_NAMESPACES_USAGE_SUCCESS = 'GET_NAMESPACES_USAGE_SUCCESS';
export const GET_NAMESPACES_USAGE_FAILURE = 'GET_NAMESPACES_USAGE_FAILURE';
