export const GET_PROFILE_BALANCE_REQUEST = 'GET_PROFILE_BALANCE_REQUEST';
export const GET_PROFILE_BALANCE_SUCCESS = 'GET_PROFILE_BALANCE_SUCCESS';
export const GET_PROFILE_BALANCE_FAILURE = 'GET_PROFILE_BALANCE_FAILURE';
