export const CHECK_HASH_PASSWORD_INVALID = 'CHECK_HASH_PASSWORD_INVALID';
export const CHECK_HASH_PASSWORD_REQUESTING = 'CHECK_HASH_PASSWORD_REQUESTING';
export const CHECK_HASH_PASSWORD_SUCCESS = 'CHECK_HASH_PASSWORD_SUCCESS';
export const CHECK_HASH_PASSWORD_FAILURE = 'CHECK_HASH_PASSWORD_FAILURE';
