export const CONFIRM_SIGNUP_INVALID = 'CONFIRM_SIGNUP_INVALID';
export const CONFIRM_SIGNUP_REQUESTING = 'CONFIRM_SIGNUP_REQUESTING';
export const CONFIRM_SIGNUP_SUCCESS = 'CONFIRM_SIGNUP_SUCCESS';
export const CONFIRM_SIGNUP_FAILURE = 'CONFIRM_SIGNUP_FAILURE';
