export const EMAIL_CONFIRM_REQUEST = 'EMAIL_CONFIRM_REQUEST';
export const EMAIL_CONFIRM_SUCCESS = 'EMAIL_CONFIRM_SUCCESS';
export const EMAIL_CONFIRM_FAILURE = 'EMAIL_CONFIRM_FAILURE';
export const CONFIRM_REQUEST = 'CONFIRM_REQUEST';
