export const CONVERT_TO_COMPANY_REQUEST = 'CONVERT_TO_COMPANY_REQUEST';
export const CONVERT_TO_COMPANY_SUCCESS = 'CONVERT_TO_COMPANY_SUCCESS';
export const CONVERT_TO_COMPANY_FAILURE = 'CONVERT_TO_COMPANY_FAILURE';
