export const CREATE_INT_SERVICE_REQUEST = 'CREATE_INT_SERVICE_REQUEST';
export const CREATE_INT_SERVICE_SUCCESS = 'CREATE_INT_SERVICE_SUCCESS';
export const CREATE_INT_SERVICE_FAILURE = 'CREATE_INT_SERVICE_FAILURE';
export const CREATE_EXT_SERVICE_REQUEST = 'CREATE_EXT_SERVICE_REQUEST';
export const CREATE_EXT_SERVICE_SUCCESS = 'CREATE_EXT_SERVICE_SUCCESS';
export const CREATE_EXT_SERVICE_FAILURE = 'CREATE_EXT_SERVICE_FAILURE';
