export const DEPLOYMENT_REQUEST = 'DEPLOYMENT_REQUEST';
export const DEPLOYMENT_SUCCESS = 'DEPLOYMENT_SUCCESS';
export const DEPLOYMENT_FAILURE = 'DEPLOYMENT_FAILURE';
export const DELETE_DEPLOYMENT_REQUEST = 'DELETE_DEPLOYMENT_REQUEST';
export const DELETE_DEPLOYMENT_SUCCESS = 'DELETE_DEPLOYMENT_SUCCESS';
export const DELETE_DEPLOYMENT_FAILURE = 'DELETE_DEPLOYMENT_FAILURE';
