export const GET_RELEASES_INVALID = 'GET_RELEASES_INVALID';
export const GET_RELEASES_REQUESTING = 'GET_RELEASES_REQUESTING';
export const GET_RELEASES_SUCCESS = 'GET_RELEASES_SUCCESS';
export const GET_RELEASES_FAILURE = 'GET_RELEASES_FAILURE';
