export const GET_STARTED_INVALID = 'GET_STARTED_INVALID';
export const GET_STARTED_REQUESTING = 'GET_STARTED_REQUESTING';
export const GET_STARTED_SUCCESS = 'GET_STARTED_SUCCESS';
export const GET_STARTED_FAILURE = 'GET_STARTED_FAILURE';
