export const DELETE_NAMESPACE_REQUEST = 'DELETE_NAMESPACE_REQUEST';
export const DELETE_NAMESPACE_SUCCESS = 'DELETE_NAMESPACE_SUCCESS';
export const DELETE_NAMESPACE_FAILURE = 'DELETE_NAMESPACE_FAILURE';

export const CREATE_NAMESPACE_REQUEST = 'CREATE_NAMESPACE_REQUEST';
export const CREATE_NAMESPACE_SUCCESS = 'CREATE_NAMESPACE_SUCCESS';
export const CREATE_NAMESPACE_FAILURE = 'CREATE_NAMESPACE_FAILURE';