export const NAMESPACES_REQUEST = 'NAMESPACES_REQUEST';
export const NAMESPACES_SUCCESS = 'NAMESPACES_SUCCESS';
export const NAMESPACES_FAILURE = 'NAMESPACES_FAILURE';

export const NSTARIFFS_REQUEST = 'NSTARIFFS_REQUEST';
export const NSTARIFFS_SUCCESS = 'NSTARIFFS_SUCCESS';
export const NSTARIFFS_FAILURE = 'NSTARIFFS_FAILURE';
