export const GET_NAMESPACE_REQUEST = 'GET_NAMESPACE_REQUEST';
export const GET_NAMESPACE_SUCCESS = 'GET_NAMESPACE_SUCCESS';
export const GET_NAMESPACE_FAILURE = 'GET_NAMESPACE_FAILURE';

export const DELETE_NAMESPACE_REQUEST = 'DELETE_NAMESPACE_REQUEST';
export const DELETE_NAMESPACE_SUCCESS = 'DELETE_NAMESPACE_SUCCESS';
export const DELETE_NAMESPACE_FAILURE = 'DELETE_NAMESPACE_FAILURE';

export const CREATE_NAMESPACE_REQUEST = 'CREATE_NAMESPACE_REQUEST';
export const CREATE_NAMESPACE_SUCCESS = 'CREATE_NAMESPACE_SUCCESS';
export const CREATE_NAMESPACE_FAILURE = 'CREATE_NAMESPACE_FAILURE';

export const UPDATE_NAMESPACE_REQUEST = 'UPDATE_NAMESPACE_REQUEST';
export const UPDATE_NAMESPACE_SUCCESS = 'UPDATE_NAMESPACE_SUCCESS';
export const UPDATE_NAMESPACE_FAILURE = 'UPDATE_NAMESPACE_FAILURE';
