export const NAMESPACES_REQUEST = 'NAMESPACES_REQUEST';
export const NAMESPACES_SUCCESS = 'NAMESPACES_SUCCESS';
export const NAMESPACES_FAILURE = 'NAMESPACES_FAILURE';
export const NAMESPACE_DELETE_REQUEST = 'NAMESPACE_DELETE_REQUEST';
export const NAMESPACE_DELETE_SUCCESS = 'NAMESPACE_DELETE_SUCCESS';
export const NAMESPACE_DELETE_FAILURE = 'NAMESPACE_DELETE_FAILURE';
