export const POD_REQUEST = 'POD_REQUEST';
export const POD_SUCCESS = 'POD_SUCCESS';
export const POD_FAILURE = 'POD_FAILURE';
export const DELETE_POD_REQUEST = 'DELETE_POD_REQUEST';
export const DELETE_POD_SUCCESS = 'DELETE_POD_SUCCESS';
export const DELETE_POD_FAILURE = 'DELETE_POD_FAILURE';
