export const RECOVERY_PASSWORD_INVALID = 'RECOVERY_PASSWORD_INVALID';
export const RECOVERY_PASSWORD_REQUESTING = 'RECOVERY_PASSWORD_REQUESTING';
export const RECOVERY_PASSWORD_SUCCESS = 'RECOVERY_PASSWORD_SUCCESS';
export const RECOVERY_PASSWORD_FAILURE = 'RECOVERY_PASSWORD_FAILURE';
