export const EMAIL_SUBSCRIPTIONS_REQUEST = 'EMAIL_SUBSCRIPTIONS_REQUEST';
export const EMAIL_SUBSCRIPTIONS_SUCCESS = 'EMAIL_SUBSCRIPTIONS_SUCCESS';
export const EMAIL_SUBSCRIPTIONS_FAILURE = 'EMAIL_SUBSCRIPTIONS_FAILURE';
