export const SUPPORT_REQUEST = 'SUPPORT_REQUEST';
export const SUPPORT_SUCCESS = 'SUPPORT_SUCCESS';
export const SUPPORT_FAILURE = 'SUPPORT_FAILURE';
export const GET_GROUP_OMNIDESK_REQUEST = 'GET_GROUP_OMNIDESK_REQUEST';
export const GET_GROUP_OMNIDESK_SUCCESS = 'GET_GROUP_OMNIDESK_SUCCESS';
export const GET_GROUP_OMNIDESK_FAILURE = 'GET_GROUP_OMNIDESK_FAILURE';
