export const TOKENS_REQUEST = 'TOKENS_REQUEST';
export const TOKENS_SUCCESS = 'TOKENS_SUCCESS';
export const TOKENS_FAILURE = 'TOKENS_FAILURE';

export const TOKEN_REQUEST = 'TOKEN_REQUEST';
export const TOKEN_SUCCESS = 'TOKEN_SUCCESS';
export const TOKEN_FAILURE = 'TOKEN_FAILURE';

export const GET_IMAGE_TOKENS_REQUEST = 'GET_IMAGE_TOKENS_REQUEST';
export const GET_IMAGE_TOKENS_SUCCESS = 'GET_IMAGE_TOKENS_SUCCESS';
export const GET_IMAGE_TOKENS_FAILURE = 'GET_IMAGE_TOKENS_FAILURE';


export const CREATE_IMAGE_TOKENS_REQUEST = 'CREATE_IMAGE_TOKENS_REQUEST';
export const CREATE_IMAGE_TOKENS_SUCCESS = 'CREATE_IMAGE_TOKENS_SUCCESS';
export const CREATE_IMAGE_TOKENS_FAILURE = 'CREATE_IMAGE_TOKENS_FAILURE';


export const DELETE_IMAGE_TOKENS_REQUEST = 'DELETE_IMAGE_TOKENS_REQUEST';
export const DELETE_IMAGE_TOKENS_SUCCESS = 'DELETE_IMAGE_TOKENS_SUCCESS';
export const DELETE_IMAGE_TOKENS_FAILURE = 'DELETE_IMAGE_TOKENS_FAILURE';
