export const TOKENS_REQUEST = 'TOKENS_REQUEST';
export const TOKENS_SUCCESS = 'TOKENS_SUCCESS';
export const TOKENS_FAILURE = 'TOKENS_FAILURE';
export const TOKEN_REQUEST = 'TOKEN_REQUEST';
export const TOKEN_SUCCESS = 'TOKEN_SUCCESS';
export const TOKEN_FAILURE = 'TOKEN_FAILURE';
