export const UPDATE_DEPLOYMENT_REQUEST = 'UPDATE_DEPLOYMENT_REQUEST';
export const UPDATE_DEPLOYMENT_SUCCESS = 'UPDATE_DEPLOYMENT_SUCCESS';
export const UPDATE_DEPLOYMENT_FAILURE = 'UPDATE_DEPLOYMENT_FAILURE';
