export const UPDATE_INT_SERVICE_REQUEST = 'UPDATE_INT_SERVICE_REQUEST';
export const UPDATE_INT_SERVICE_SUCCESS = 'UPDATE_INT_SERVICE_SUCCESS';
export const UPDATE_INT_SERVICE_FAILURE = 'UPDATE_INT_SERVICE_FAILURE';
export const UPDATE_EXT_SERVICE_REQUEST = 'UPDATE_EXT_SERVICE_REQUEST';
export const UPDATE_EXT_SERVICE_SUCCESS = 'UPDATE_EXT_SERVICE_SUCCESS';
export const UPDATE_EXT_SERVICE_FAILURE = 'UPDATE_EXT_SERVICE_FAILURE';
