export const USER_HASH_CONFIRM_REQUEST = 'USER_HASH_CONFIRM_REQUEST';
export const USER_HASH_CONFIRM_SUCCESS = 'USER_HASH_CONFIRM_SUCCESS';
export const USER_HASH_CONFIRM_FAILURE = 'USER_HASH_CONFIRM_FAILURE';
