export const VALIDATE_EMAIL = 'VALIDATE_EMAIL';
export const NOT_VALIDATE_EMAIL = 'NOT_VALIDATE_EMAIL';
export const VALIDATE_PASSWORD = 'VALIDATE_PASSWORD';
export const NOT_VALIDATE_PASSWORD = 'NOT_VALIDATE_PASSWORD';