export const GET_VOLUME_REQUEST = 'GET_VOLUME_REQUEST';
export const GET_VOLUME_SUCCESS = 'GET_VOLUME_SUCCESS';
export const GET_VOLUME_FAILURE = 'GET_VOLUME_FAILURE';

export const DELETE_VOLUME_REQUEST = 'DELETE_VOLUME_REQUEST';
export const DELETE_VOLUME_SUCCESS = 'DELETE_VOLUME_SUCCESS';
export const DELETE_VOLUME_FAILURE = 'DELETE_VOLUME_FAILURE';

export const CREATE_VOLUME_REQUEST = 'CREATE_VOLUME_REQUEST';
export const CREATE_VOLUME_SUCCESS = 'CREATE_VOLUME_SUCCESS';
export const CREATE_VOLUME_FAILURE = 'CREATE_VOLUME_FAILURE';

export const UPDATE_VOLUME_REQUEST = 'UPDATE_VOLUME_REQUEST';
export const UPDATE_VOLUME_SUCCESS = 'UPDATE_VOLUME_SUCCESS';
export const UPDATE_VOLUME_FAILURE = 'UPDATE_VOLUME_FAILURE';
