export const VOLUMES_REQUEST = 'VOLUMES_REQUEST';
export const VOLUMES_SUCCESS = 'VOLUMES_SUCCESS';
export const VOLUMES_FAILURE = 'VOLUMES_FAILURE';
export const VOLUMES_TARIFFS_REQUEST = 'VOLUMES_TARIFFS_REQUEST';
export const VOLUMES_TARIFFS_SUCCESS = 'VOLUMES_TARIFFS_SUCCESS';
export const VOLUMES_TARIFFS_FAILURE = 'VOLUMES_TARIFFS_FAILURE';
