export const ACTIVATE_USER_INVALID = 'ACTIVATE_USER_INVALID';
export const ACTIVATE_USER_REQUESTING = 'ACTIVATE_USER_REQUESTING';
export const ACTIVATE_USER_SUCCESS = 'ACTIVATE_USER_SUCCESS';
export const ACTIVATE_USER_FAILURE = 'ACTIVATE_USER_FAILURE';
