export const DEACTIVATE_USER_INVALID = 'DEACTIVATE_USER_INVALID';
export const DEACTIVATE_USER_REQUESTING = 'DEACTIVATE_USER_REQUESTING';
export const DEACTIVATE_USER_SUCCESS = 'DEACTIVATE_USER_SUCCESS';
export const DEACTIVATE_USER_FAILURE = 'DEACTIVATE_USER_FAILURE';
