export const RESET_PASSWORD_OF_USER_INVALID = 'RESET_PASSWORD_OF_USER_INVALID';
export const RESET_PASSWORD_OF_USER_REQUESTING =
  'RESET_PASSWORD_OF_USER_REQUESTING';
export const RESET_PASSWORD_OF_USER_SUCCESS = 'RESET_PASSWORD_OF_USER_SUCCESS';
export const RESET_PASSWORD_OF_USER_FAILURE = 'RESET_PASSWORD_OF_USER_FAILURE';
