export const SET_USER_AS_ADMIN_INVALID = 'SET_USER_AS_ADMIN_INVALID';
export const SET_USER_AS_ADMIN_REQUESTING = 'SET_USER_AS_ADMIN_REQUESTING';
export const SET_USER_AS_ADMIN_SUCCESS = 'SET_USER_AS_ADMIN_SUCCESS';
export const SET_USER_AS_ADMIN_FAILURE = 'SET_USER_AS_ADMIN_FAILURE';
