export const UNSET_USER_AS_ADMIN_INVALID = 'UNSET_USER_AS_ADMIN_INVALID';
export const UNSET_USER_AS_ADMIN_REQUESTING = 'UNSET_USER_AS_ADMIN_REQUESTING';
export const UNSET_USER_AS_ADMIN_SUCCESS = 'UNSET_USER_AS_ADMIN_SUCCESS';
export const UNSET_USER_AS_ADMIN_FAILURE = 'UNSET_USER_AS_ADMIN_FAILURE';
