export const GET_DEPLOYMENTS_INVALID = 'GET_DEPLOYMENTS_INVALID';
export const GET_DEPLOYMENTS_REQUESTING = 'GET_DEPLOYMENTS_REQUESTING';
export const GET_DEPLOYMENTS_SUCCESS = 'GET_DEPLOYMENTS_SUCCESS';
export const GET_DEPLOYMENTS_FAILURE = 'GET_DEPLOYMENTS_FAILURE';
