export const GET_STATUS_INVALID = 'GET_STATUS_INVALID';
export const GET_STATUS_REQUESTING = 'GET_STATUS_REQUESTING';
export const GET_STATUS_SUCCESS = 'GET_STATUS_SUCCESS';
export const GET_STATUS_FAILURE = 'GET_STATUS_FAILURE';
