export const CREATE_DOMAIN_INVALID = 'CREATE_DOMAIN_INVALID';
export const CREATE_DOMAIN_REQUESTING = 'CREATE_DOMAIN_REQUESTING';
export const CREATE_DOMAIN_SUCCESS = 'CREATE_DOMAIN_SUCCESS';
export const CREATE_DOMAIN_FAILURE = 'CREATE_DOMAIN_FAILURE';
