export const CREATE_EXTERNAL_SERVICE_INVALID =
  'CREATE_EXTERNAL_SERVICE_INVALID';
export const CREATE_EXTERNAL_SERVICE_REQUESTING =
  'CREATE_EXTERNAL_SERVICE_REQUESTING';
export const CREATE_EXTERNAL_SERVICE_SUCCESS =
  'CREATE_EXTERNAL_SERVICE_SUCCESS';
export const CREATE_EXTERNAL_SERVICE_FAILURE =
  'CREATE_EXTERNAL_SERVICE_FAILURE';
