export const CREATE_INTERNAL_SERVICE_INVALID =
  'CREATE_INTERNAL_SERVICE_INVALID';
export const CREATE_INTERNAL_SERVICE_REQUESTING =
  'CREATE_INTERNAL_SERVICE_REQUESTING';
export const CREATE_INTERNAL_SERVICE_SUCCESS =
  'CREATE_INTERNAL_SERVICE_SUCCESS';
export const CREATE_INTERNAL_SERVICE_FAILURE =
  'CREATE_INTERNAL_SERVICE_FAILURE';
