export const DELETE_SERVICE_INVALID = 'DELETE_SERVICE_INVALID';
export const DELETE_SERVICE_REQUESTING = 'DELETE_SERVICE_REQUESTING';
export const DELETE_SERVICE_SUCCESS = 'DELETE_SERVICE_SUCCESS';
export const DELETE_SERVICE_FAILURE = 'DELETE_SERVICE_FAILURE';
