export const DELETE_DOMAIN_INVALID = 'DELETE_DOMAIN_INVALID';
export const DELETE_DOMAIN_REQUESTING = 'DELETE_DOMAIN_REQUESTING';
export const DELETE_DOMAIN_SUCCESS = 'DELETE_DOMAIN_SUCCESS';
export const DELETE_DOMAIN_FAILURE = 'DELETE_DOMAIN_FAILURE';
