export const DELETE_INGRESS_INVALID = 'DELETE_INGRESS_INVALID';
export const DELETE_INGRESS_REQUESTING = 'DELETE_INGRESS_REQUESTING';
export const DELETE_INGRESS_SUCCESS = 'DELETE_INGRESS_SUCCESS';
export const DELETE_INGRESS_FAILURE = 'DELETE_INGRESS_FAILURE';
