export const GET_INGRESSES_INVALID = 'GET_INGRESSES_INVALID';
export const GET_INGRESSES_REQUESTING = 'GET_INGRESSES_REQUESTING';
export const GET_INGRESSES_SUCCESS = 'GET_INGRESSES_SUCCESS';
export const GET_INGRESSES_FAILURE = 'GET_INGRESSES_FAILURE';
