export const GET_DOMAINS_INVALID = 'GET_DOMAINS_INVALID';
export const GET_DOMAINS_REQUESTING = 'GET_DOMAINS_REQUESTING';
export const GET_DOMAINS_SUCCESS = 'GET_DOMAINS_SUCCESS';
export const GET_DOMAINS_FAILURE = 'GET_DOMAINS_FAILURE';
