export const GET_DOMAINS_GLOBAL_INVALID = 'GET_DOMAINS_GLOBAL_INVALID';
export const GET_DOMAINS_GLOBAL_REQUESTING = 'GET_DOMAINS_GLOBAL_REQUESTING';
export const GET_DOMAINS_GLOBAL_SUCCESS = 'GET_DOMAINS_GLOBAL_SUCCESS';
export const GET_DOMAINS_GLOBAL_FAILURE = 'GET_DOMAINS_GLOBAL_FAILURE';
