export const GET_SERVICE_INVALID = 'GET_SERVICE_INVALID';
export const GET_SERVICE_REQUESTING = 'GET_SERVICE_REQUESTING';
export const GET_SERVICE_SUCCESS = 'GET_SERVICE_SUCCESS';
export const GET_SERVICE_FAILURE = 'GET_SERVICE_FAILURE';
