export const UPDATE_EXTERNAL_SERVICE_INVALID =
  'UPDATE_EXTERNAL_SERVICE_INVALID';
export const UPDATE_EXTERNAL_SERVICE_REQUESTING =
  'UPDATE_EXTERNAL_SERVICE_REQUESTING';
export const UPDATE_EXTERNAL_SERVICE_SUCCESS =
  'UPDATE_EXTERNAL_SERVICE_SUCCESS';
export const UPDATE_EXTERNAL_SERVICE_FAILURE =
  'UPDATE_EXTERNAL_SERVICE_FAILURE';
