export const UPDATE_INTERNAL_SERVICE_INVALID =
  'UPDATE_INTERNAL_SERVICE_INVALID';
export const UPDATE_INTERNAL_SERVICE_REQUESTING =
  'UPDATE_INTERNAL_SERVICE_REQUESTING';
export const UPDATE_INTERNAL_SERVICE_SUCCESS =
  'UPDATE_INTERNAL_SERVICE_SUCCESS';
export const UPDATE_INTERNAL_SERVICE_FAILURE =
  'UPDATE_INTERNAL_SERVICE_FAILURE';
