export const ADMIN_DELETE_USER_INVALID = 'ADMIN_DELETE_USER_INVALID';
export const ADMIN_DELETE_USER_REQUESTING = 'ADMIN_DELETE_USER_REQUESTING';
export const ADMIN_DELETE_USER_SUCCESS = 'ADMIN_DELETE_USER_SUCCESS';
export const ADMIN_DELETE_USER_FAILURE = 'ADMIN_DELETE_USER_FAILURE';
