export const GET_USERLIST_INVALID = 'GET_USERLIST_INVALID';
export const GET_USERLIST_REQUESTING = 'GET_USERLIST_REQUESTING';
export const GET_USERLIST_SUCCESS = 'GET_USERLIST_SUCCESS';
export const GET_USERLIST_FAILURE = 'GET_USERLIST_FAILURE';
