export const ADD_NAMESPACE_USER_ACCESS_INVALID =
  'ADD_NAMESPACE_USER_ACCESS_INVALID';
export const ADD_NAMESPACE_USER_ACCESS_REQUESTING =
  'ADD_NAMESPACE_USER_ACCESS_REQUESTING';
export const ADD_NAMESPACE_USER_ACCESS_SUCCESS =
  'ADD_NAMESPACE_USER_ACCESS_SUCCESS';
export const ADD_NAMESPACE_USER_ACCESS_FAILURE =
  'ADD_NAMESPACE_USER_ACCESS_FAILURE';
