export const CREATE_NAMESPACE_INVALID = 'CREATE_NAMESPACE_INVALID';
export const CREATE_NAMESPACE_REQUESTING = 'CREATE_NAMESPACE_REQUESTING';
export const CREATE_NAMESPACE_SUCCESS = 'CREATE_NAMESPACE_SUCCESS';
export const CREATE_NAMESPACE_FAILURE = 'CREATE_NAMESPACE_FAILURE';
