export const CREATE_CUSTOM_NAMESPACE_INVALID =
  'CREATE_CUSTOM_NAMESPACE_INVALID';
export const CREATE_CUSTOM_NAMESPACE_REQUESTING =
  'CREATE_CUSTOM_NAMESPACE_REQUESTING';
export const CREATE_CUSTOM_NAMESPACE_SUCCESS =
  'CREATE_CUSTOM_NAMESPACE_SUCCESS';
export const CREATE_CUSTOM_NAMESPACE_FAILURE =
  'CREATE_CUSTOM_NAMESPACE_FAILURE';
