export const DELETE_NAMESPACE_INVALID = 'DELETE_NAMESPACE_INVALID';
export const DELETE_NAMESPACE_REQUESTING = 'DELETE_NAMESPACE_REQUESTING';
export const DELETE_NAMESPACE_SUCCESS = 'DELETE_NAMESPACE_SUCCESS';
export const DELETE_NAMESPACE_FAILURE = 'DELETE_NAMESPACE_FAILURE';
