export const DELETE_NAMESPACE_USER_ACCESS_INVALID =
  'DELETE_NAMESPACE_USER_ACCESS_INVALID';
export const DELETE_NAMESPACE_USER_ACCESS_REQUESTING =
  'DELETE_NAMESPACE_USER_ACCESS_REQUESTING';
export const DELETE_NAMESPACE_USER_ACCESS_SUCCESS =
  'DELETE_NAMESPACE_USER_ACCESS_SUCCESS';
export const DELETE_NAMESPACE_USER_ACCESS_FAILURE =
  'DELETE_NAMESPACE_USER_ACCESS_FAILURE';
