export const GET_NAMESPACE_ACCESS_INVALID = 'GET_NAMESPACE_ACCESS_INVALID';
export const GET_NAMESPACE_ACCESS_REQUESTING =
  'GET_NAMESPACE_ACCESS_REQUESTING';
export const GET_NAMESPACE_ACCESS_SUCCESS = 'GET_NAMESPACE_ACCESS_SUCCESS';
export const GET_NAMESPACE_ACCESS_FAILURE = 'GET_NAMESPACE_ACCESS_FAILURE';
