export const GET_NAMESPACE_INVALID = 'GET_NAMESPACE_INVALID';
export const GET_NAMESPACE_REQUESTING = 'GET_NAMESPACE_REQUESTING';
export const GET_NAMESPACE_SUCCESS = 'GET_NAMESPACE_SUCCESS';
export const GET_NAMESPACE_FAILURE = 'GET_NAMESPACE_FAILURE';
