export const RESIZE_NAMESPACE_INVALID = 'RESIZE_NAMESPACE_INVALID';
export const RESIZE_NAMESPACE_REQUESTING = 'RESIZE_NAMESPACE_REQUESTING';
export const RESIZE_NAMESPACE_SUCCESS = 'RESIZE_NAMESPACE_SUCCESS';
export const RESIZE_NAMESPACE_FAILURE = 'RESIZE_NAMESPACE_FAILURE';
