export const UPDATE_CUSTOM_NAMESPACE_INVALID =
  'UPDATE_CUSTOM_NAMESPACE_INVALID';
export const UPDATE_CUSTOM_NAMESPACE_REQUESTING =
  'UPDATE_CUSTOM_NAMESPACE_REQUESTING';
export const UPDATE_CUSTOM_NAMESPACE_SUCCESS =
  'UPDATE_CUSTOM_NAMESPACE_SUCCESS';
export const UPDATE_CUSTOM_NAMESPACE_FAILURE =
  'UPDATE_CUSTOM_NAMESPACE_FAILURE';
