export const CHANGE_PROFILE_INFO_INVALID = 'CHANGE_PROFILE_INFO_INVALID';
export const CHANGE_PROFILE_INFO_REQUESTING = 'CHANGE_PROFILE_INFO_REQUESTING';
export const CHANGE_PROFILE_INFO_SUCCESS = 'CHANGE_PROFILE_INFO_SUCCESS';
export const CHANGE_PROFILE_INFO_FAILURE = 'CHANGE_PROFILE_INFO_FAILURE';
