export const CHANGE_PASSWORD_INVALID = 'CHANGE_PASSWORD_INVALID';
export const CHANGE_PASSWORD_REQUESTING = 'CHANGE_PASSWORD_REQUESTING';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_FAILURE = 'CHANGE_PASSWORD_FAILURE';
