export const DELETE_ACCOUNT_INVALID = 'DELETE_ACCOUNT_INVALID';
export const DELETE_ACCOUNT_REQUESTING = 'DELETE_ACCOUNT_REQUESTING';
export const DELETE_ACCOUNT_SUCCESS = 'DELETE_ACCOUNT_SUCCESS';
export const DELETE_ACCOUNT_FAILURE = 'DELETE_ACCOUNT_FAILURE';
