export const GET_PROFILE_TARIFFS_INVALID = 'GET_PROFILE_TARIFFS_INVALID';
export const GET_PROFILE_TARIFFS_REQUESTING = 'GET_PROFILE_TARIFFS_REQUESTING';
export const GET_PROFILE_TARIFFS_SUCCESS = 'GET_PROFILE_TARIFFS_SUCCESS';
export const GET_PROFILE_TARIFFS_FAILURE = 'GET_PROFILE_TARIFFS_FAILURE';
