export const GET_PROFILE_INVALID = 'GET_PROFILE_INVALID';
export const GET_PROFILE_REQUESTING = 'GET_PROFILE_REQUESTING';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILE_FAILURE = 'GET_PROFILE_FAILURE';
