export const GET_PROFILE_REPORT_INVALID = 'GET_PROFILE_REPORT_INVALID';
export const GET_PROFILE_REPORT_REQUESTING = 'GET_PROFILE_REPORT_REQUESTING';
export const GET_PROFILE_REPORT_SUCCESS = 'GET_PROFILE_REPORT_SUCCESS';
export const GET_PROFILE_REPORT_FAILURE = 'GET_PROFILE_REPORT_FAILURE';
