export const GET_USER_PROFILE_BY_EMAIL_INVALID =
  'GET_USER_PROFILE_BY_EMAIL_INVALID';
export const GET_USER_PROFILE_BY_EMAIL_REQUESTING =
  'GET_USER_PROFILE_BY_EMAIL_REQUESTING';
export const GET_USER_PROFILE_BY_EMAIL_SUCCESS =
  'GET_USER_PROFILE_BY_EMAIL_SUCCESS';
export const GET_USER_PROFILE_BY_EMAIL_FAILURE =
  'GET_USER_PROFILE_BY_EMAIL_FAILURE';
