export const CREATE_CONFIG_MAP_INVALID = 'CREATE_CONFIG_MAP_INVALID';
export const CREATE_CONFIG_MAP_REQUESTING = 'CREATE_CONFIG_MAP_REQUESTING';
export const CREATE_CONFIG_MAP_SUCCESS = 'CREATE_CONFIG_MAP_SUCCESS';
export const CREATE_CONFIG_MAP_FAILURE = 'CREATE_CONFIG_MAP_FAILURE';
