export const DELETE_CONFIG_MAP_INVALID = 'DELETE_CONFIG_MAP_INVALID';
export const DELETE_CONFIG_MAP_REQUESTING = 'DELETE_CONFIG_MAP_REQUESTING';
export const DELETE_CONFIG_MAP_SUCCESS = 'DELETE_CONFIG_MAP_SUCCESS';
export const DELETE_CONFIG_MAP_FAILURE = 'DELETE_CONFIG_MAP_FAILURE';
