export const GET_CONFIG_MAP_INVALID = 'GET_CONFIG_MAP_INVALID';
export const GET_CONFIG_MAP_REQUESTING = 'GET_CONFIG_MAP_REQUESTING';
export const GET_CONFIG_MAP_SUCCESS = 'GET_CONFIG_MAP_SUCCESS';
export const GET_CONFIG_MAP_FAILURE = 'GET_CONFIG_MAP_FAILURE';
