export const GET_CONFIG_MAPS_BY_NS_INVALID = 'GET_CONFIG_MAPS_BY_NS_INVALID';
export const GET_CONFIG_MAPS_BY_NS_REQUESTING =
  'GET_CONFIG_MAPS_BY_NS_REQUESTING';
export const GET_CONFIG_MAPS_BY_NS_SUCCESS = 'GET_CONFIG_MAPS_BY_NS_SUCCESS';
export const GET_CONFIG_MAPS_BY_NS_FAILURE = 'GET_CONFIG_MAPS_BY_NS_FAILURE';
