export const GET_CONFIG_MAPS_INVALID = 'GET_CONFIG_MAPS_INVALID';
export const GET_CONFIG_MAPS_REQUESTING = 'GET_CONFIG_MAPS_REQUESTING';
export const GET_CONFIG_MAPS_SUCCESS = 'GET_CONFIG_MAPS_SUCCESS';
export const GET_CONFIG_MAPS_FAILURE = 'GET_CONFIG_MAPS_FAILURE';
