export const CREATE_VOLUME_INVALID = 'CREATE_VOLUME_INVALID';
export const CREATE_VOLUME_REQUESTING = 'CREATE_VOLUME_REQUESTING';
export const CREATE_VOLUME_SUCCESS = 'CREATE_VOLUME_SUCCESS';
export const CREATE_VOLUME_FAILURE = 'CREATE_VOLUME_FAILURE';
