export const CREATE_CUSTOM_VOLUME_INVALID = 'CREATE_CUSTOM_VOLUME_INVALID';
export const CREATE_CUSTOM_VOLUME_REQUESTING =
  'CREATE_CUSTOM_VOLUME_REQUESTING';
export const CREATE_CUSTOM_VOLUME_SUCCESS = 'CREATE_CUSTOM_VOLUME_SUCCESS';
export const CREATE_CUSTOM_VOLUME_FAILURE = 'CREATE_CUSTOM_VOLUME_FAILURE';
