export const DELETE_VOLUME_INVALID = 'DELETE_VOLUME_INVALID';
export const DELETE_VOLUME_REQUESTING = 'DELETE_VOLUME_REQUESTING';
export const DELETE_VOLUME_SUCCESS = 'DELETE_VOLUME_SUCCESS';
export const DELETE_VOLUME_FAILURE = 'DELETE_VOLUME_FAILURE';
