export const GET_VOLUME_INVALID = 'GET_VOLUME_INVALID';
export const GET_VOLUME_REQUESTING = 'GET_VOLUME_REQUESTING';
export const GET_VOLUME_SUCCESS = 'GET_VOLUME_SUCCESS';
export const GET_VOLUME_FAILURE = 'GET_VOLUME_FAILURE';
