export const RESIZE_VOLUME_INVALID = 'RESIZE_VOLUME_INVALID';
export const RESIZE_VOLUME_REQUESTING = 'RESIZE_VOLUME_REQUESTING';
export const RESIZE_VOLUME_SUCCESS = 'RESIZE_VOLUME_SUCCESS';
export const RESIZE_VOLUME_FAILURE = 'RESIZE_VOLUME_FAILURE';
