export const UPDATE_CUSTOM_VOLUME_INVALID = 'UPDATE_CUSTOM_VOLUME_INVALID';
export const UPDATE_CUSTOM_VOLUME_REQUESTING =
  'UPDATE_CUSTOM_VOLUME_REQUESTING';
export const UPDATE_CUSTOM_VOLUME_SUCCESS = 'UPDATE_CUSTOM_VOLUME_SUCCESS';
export const UPDATE_CUSTOM_VOLUME_FAILURE = 'UPDATE_CUSTOM_VOLUME_FAILURE';
