export const CREATE_IMAGE_TOKEN_INVALID = 'CREATE_IMAGE_TOKEN_INVALID';
export const CREATE_IMAGE_TOKEN_REQUESTING = 'CREATE_IMAGE_TOKEN_REQUESTING';
export const CREATE_IMAGE_TOKEN_SUCCESS = 'CREATE_IMAGE_TOKEN_SUCCESS';
export const CREATE_IMAGE_TOKEN_FAILURE = 'CREATE_IMAGE_TOKEN_FAILURE';
