export const DELETE_IMAGE_TOKEN_INVALID = 'DELETE_IMAGE_TOKEN_INVALID';
export const DELETE_IMAGE_TOKEN_REQUESTING = 'DELETE_IMAGE_TOKEN_REQUESTING';
export const DELETE_IMAGE_TOKEN_SUCCESS = 'DELETE_IMAGE_TOKEN_SUCCESS';
export const DELETE_IMAGE_TOKEN_FAILURE = 'DELETE_IMAGE_TOKEN_FAILURE';
