export const GET_IMAGES_TOKEN_INVALID = 'GET_IMAGES_TOKEN_INVALID';
export const GET_IMAGES_TOKEN_REQUESTING = 'GET_IMAGES_TOKEN_REQUESTING';
export const GET_IMAGES_TOKEN_SUCCESS = 'GET_IMAGES_TOKEN_SUCCESS';
export const GET_IMAGES_TOKEN_FAILURE = 'GET_IMAGES_TOKEN_FAILURE';
