replicaCount: 1

image:
  repository: containerum/ui
  tag: v1.0.0
  pullPolicy: IfNotPresent
  secret:

service:
  port: 3000
  targetPort: 3000
  externalIP:

env:
  global:
    COUNTRY: US
    SOURCE_TYPE: LOCAL
    ## for HTTPS use: ssl
    API_PROTOCOL_TYPE: no-ssl
  local:
    API_HOST: null
    API_PORT: "8082"
    RECAPTCHA: null
