export const ADD_DOMAIN_INVALID = 'ADD_DOMAIN_INVALID';
export const ADD_DOMAIN_REQUESTING = 'ADD_DOMAIN_REQUESTING';
export const ADD_DOMAIN_SUCCESS = 'ADD_DOMAIN_SUCCESS';
export const ADD_DOMAIN_FAILURE = 'ADD_DOMAIN_FAILURE';
