export const ADD_SOLUTION_INVALID = 'ADD_SOLUTION_INVALID';
export const ADD_SOLUTION_REQUESTING = 'ADD_SOLUTION_REQUESTING';
export const ADD_SOLUTION_SUCCESS = 'ADD_SOLUTION_SUCCESS';
export const ADD_SOLUTION_FAILURE = 'ADD_SOLUTION_FAILURE';
