export const DELETE_SOLUTION_INVALID = 'DELETE_SOLUTION_INVALID';
export const DELETE_SOLUTION_REQUESTING = 'DELETE_SOLUTION_REQUESTING';
export const DELETE_SOLUTION_SUCCESS = 'DELETE_SOLUTION_SUCCESS';
export const DELETE_SOLUTION_FAILURE = 'DELETE_SOLUTION_FAILURE';
