export const DELETE_RUNNING_SOLUTION_INVALID =
  'DELETE_RUNNING_SOLUTION_INVALID';
export const DELETE_RUNNING_SOLUTION_REQUESTING =
  'DELETE_RUNNING_SOLUTION_REQUESTING';
export const DELETE_RUNNING_SOLUTION_SUCCESS =
  'DELETE_RUNNING_SOLUTION_SUCCESS';
export const DELETE_RUNNING_SOLUTION_FAILURE =
  'DELETE_RUNNING_SOLUTION_FAILURE';
