export const GET_ENVS_SOLUTION_INVALID = 'GET_ENVS_SOLUTION_INVALID';
export const GET_ENVS_SOLUTION_REQUESTING = 'GET_ENVS_SOLUTION_REQUESTING';
export const GET_ENVS_SOLUTION_SUCCESS = 'GET_ENVS_SOLUTION_SUCCESS';
export const GET_ENVS_SOLUTION_FAILURE = 'GET_ENVS_SOLUTION_FAILURE';
