export const GET_SOLUTION_INVALID = 'GET_SOLUTION_INVALID';
export const GET_SOLUTION_REQUESTING = 'GET_SOLUTION_REQUESTING';
export const GET_SOLUTION_SUCCESS = 'GET_SOLUTION_SUCCESS';
export const GET_SOLUTION_FAILURE = 'GET_SOLUTION_FAILURE';
