export const RUN_SOLUTION_INVALID = 'RUN_SOLUTION_INVALID';
export const RUN_SOLUTION_REQUESTING = 'RUN_SOLUTION_REQUESTING';
export const RUN_SOLUTION_SUCCESS = 'RUN_SOLUTION_SUCCESS';
export const RUN_SOLUTION_FAILURE = 'RUN_SOLUTION_FAILURE';
