export const GET_SERVICES_INVALID = 'GET_SERVICES_INVALID';
export const GET_SERVICES_REQUESTING = 'GET_SERVICES_REQUESTING';
export const GET_SERVICES_SUCCESS = 'GET_SERVICES_SUCCESS';
export const GET_SERVICES_FAILURE = 'GET_SERVICES_FAILURE';
