export const GET_VOLUMES_TARIFFS_INVALID = 'GET_VOLUMES_TARIFFS_INVALID';
export const GET_VOLUMES_TARIFFS_REQUESTING = 'GET_VOLUMES_TARIFFS_REQUESTING';
export const GET_VOLUMES_TARIFFS_SUCCESS = 'GET_VOLUMES_TARIFFS_SUCCESS';
export const GET_VOLUMES_TARIFFS_FAILURE = 'GET_VOLUMES_TARIFFS_FAILURE';
