export const GET_VOLUMES_BY_NS_INVALID = 'GET_VOLUMES_BY_NS_INVALID';
export const GET_VOLUMES_BY_NS_REQUESTING = 'GET_VOLUMES_BY_NS_REQUESTING';
export const GET_VOLUMES_BY_NS_SUCCESS = 'GET_VOLUMES_BY_NS_SUCCESS';
export const GET_VOLUMES_BY_NS_FAILURE = 'GET_VOLUMES_BY_NS_FAILURE';
