export const GET_VOLUMES_INVALID = 'GET_VOLUMES_INVALID';
export const GET_VOLUMES_REQUESTING = 'GET_VOLUMES_REQUESTING';
export const GET_VOLUMES_SUCCESS = 'GET_VOLUMES_SUCCESS';
export const GET_VOLUMES_FAILURE = 'GET_VOLUMES_FAILURE';
