export const ADD_GLOBAL_USER_INVALID = 'ADD_GLOBAL_USER_INVALID';
export const ADD_GLOBAL_USER_REQUESTING = 'ADD_GLOBAL_USER_REQUESTING';
export const ADD_GLOBAL_USER_SUCCESS = 'ADD_GLOBAL_USER_SUCCESS';
export const ADD_GLOBAL_USER_FAILURE = 'ADD_GLOBAL_USER_FAILURE';
