export const ADD_GROUP_INVALID = 'ADD_GROUP_INVALID';
export const ADD_GROUP_REQUESTING = 'ADD_GROUP_REQUESTING';
export const ADD_GROUP_SUCCESS = 'ADD_GROUP_SUCCESS';
export const ADD_GROUP_FAILURE = 'ADD_GROUP_FAILURE';
