export const ADD_GLOBAL_USER_IN_GROUP_INVALID =
  'ADD_GLOBAL_USER_IN_GROUP_INVALID';
export const ADD_GLOBAL_USER_IN_GROUP_REQUESTING =
  'ADD_GLOBAL_USER_IN_GROUP_REQUESTING';
export const ADD_GLOBAL_USER_IN_GROUP_SUCCESS =
  'ADD_GLOBAL_USER_IN_GROUP_SUCCESS';
export const ADD_GLOBAL_USER_IN_GROUP_FAILURE =
  'ADD_GLOBAL_USER_IN_GROUP_FAILURE';
