export const DELETE_GROUP_INVALID = 'DELETE_GROUP_INVALID';
export const DELETE_GROUP_REQUESTING = 'DELETE_GROUP_REQUESTING';
export const DELETE_GROUP_SUCCESS = 'DELETE_GROUP_SUCCESS';
export const DELETE_GROUP_FAILURE = 'DELETE_GROUP_FAILURE';
