export const DELETE_USER_FROM_GROUP_INVALID = 'DELETE_USER_FROM_GROUP_INVALID';
export const DELETE_USER_FROM_GROUP_REQUESTING =
  'DELETE_USER_FROM_GROUP_REQUESTING';
export const DELETE_USER_FROM_GROUP_SUCCESS = 'DELETE_USER_FROM_GROUP_SUCCESS';
export const DELETE_USER_FROM_GROUP_FAILURE = 'DELETE_USER_FROM_GROUP_FAILURE';
