export const GET_GROUP_INVALID = 'GET_GROUP_INVALID';
export const GET_GROUP_REQUESTING = 'GET_GROUP_REQUESTING';
export const GET_GROUP_SUCCESS = 'GET_GROUP_SUCCESS';
export const GET_GROUP_FAILURE = 'GET_GROUP_FAILURE';
