export const GET_GROUPS_INVALID = 'GET_GROUPS_INVALID';
export const GET_GROUPS_REQUESTING = 'GET_GROUPS_REQUESTING';
export const GET_GROUPS_SUCCESS = 'GET_GROUPS_SUCCESS';
export const GET_GROUPS_FAILURE = 'GET_GROUPS_FAILURE';
