export const GET_USER_LIST_INVALID = 'GET_USER_LIST_INVALID';
export const GET_USER_LIST_REQUESTING = 'GET_USER_LIST_REQUESTING';
export const GET_USER_LIST_SUCCESS = 'GET_USER_LIST_SUCCESS';
export const GET_USER_LIST_FAILURE = 'GET_USER_LIST_FAILURE';
