export const UPDATE_GLOBAL_USER_IN_GROUP_INVALID =
  'UPDATE_GLOBAL_USER_IN_GROUP_INVALID';
export const UPDATE_GLOBAL_USER_IN_GROUP_REQUESTING =
  'UPDATE_GLOBAL_USER_IN_GROUP_REQUESTING';
export const UPDATE_GLOBAL_USER_IN_GROUP_SUCCESS =
  'UPDATE_GLOBAL_USER_IN_GROUP_SUCCESS';
export const UPDATE_GLOBAL_USER_IN_GROUP_FAILURE =
  'UPDATE_GLOBAL_USER_IN_GROUP_FAILURE';
