export const GET_DEPLOYMENTS_RUNNING_SOLUTION_INVALID =
  'GET_DEPLOYMENTS_RUNNING_SOLUTION_INVALID';
export const GET_DEPLOYMENTS_RUNNING_SOLUTION_REQUESTING =
  'GET_DEPLOYMENTS_RUNNING_SOLUTION_REQUESTING';
export const GET_DEPLOYMENTS_RUNNING_SOLUTION_SUCCESS =
  'GET_DEPLOYMENTS_RUNNING_SOLUTION_SUCCESS';
export const GET_DEPLOYMENTS_RUNNING_SOLUTION_FAILURE =
  'GET_DEPLOYMENTS_RUNNING_SOLUTION_FAILURE';
