export const GET_RUNNING_SOLUTIONS_INVALID = 'GET_RUNNING_SOLUTIONS_INVALID';
export const GET_RUNNING_SOLUTIONS_REQUESTING =
  'GET_RUNNING_SOLUTIONS_REQUESTING';
export const GET_RUNNING_SOLUTIONS_SUCCESS = 'GET_RUNNING_SOLUTIONS_SUCCESS';
export const GET_RUNNING_SOLUTIONS_FAILURE = 'GET_RUNNING_SOLUTIONS_FAILURE';
