export const GET_SERVICES_RUNNING_SOLUTION_INVALID =
  'GET_SERVICES_RUNNING_SOLUTION_INVALID';
export const GET_SERVICES_RUNNING_SOLUTION_REQUESTING =
  'GET_SERVICES_RUNNING_SOLUTION_REQUESTING';
export const GET_SERVICES_RUNNING_SOLUTION_SUCCESS =
  'GET_SERVICES_RUNNING_SOLUTION_SUCCESS';
export const GET_SERVICES_RUNNING_SOLUTION_FAILURE =
  'GET_SERVICES_RUNNING_SOLUTION_FAILURE';
