export const GET_SOLUTIONS_INVALID = 'GET_SOLUTIONS_INVALID';
export const GET_SOLUTIONS_REQUESTING = 'GET_SOLUTIONS_REQUESTING';
export const GET_SOLUTIONS_SUCCESS = 'GET_SOLUTIONS_SUCCESS';
export const GET_SOLUTIONS_FAILURE = 'GET_SOLUTIONS_FAILURE';
