export const GET_SUPPORT_GROUPS_INVALID = 'GET_SUPPORT_GROUPS_INVALID';
export const GET_SUPPORT_GROUPS_REQUESTING = 'GET_SUPPORT_GROUPS_REQUESTING';
export const GET_SUPPORT_GROUPS_SUCCESS = 'GET_SUPPORT_GROUPS_SUCCESS';
export const GET_SUPPORT_GROUPS_FAILURE = 'GET_SUPPORT_GROUPS_FAILURE';
