export const SEND_SUPPORT_TICKET_INVALID = 'SEND_SUPPORT_TICKET_INVALID';
export const SEND_SUPPORT_TICKET_REQUESTING = 'SEND_SUPPORT_TICKET_REQUESTING';
export const SEND_SUPPORT_TICKET_SUCCESS = 'SEND_SUPPORT_TICKET_SUCCESS';
export const SEND_SUPPORT_TICKET_FAILURE = 'SEND_SUPPORT_TICKET_FAILURE';
